first update
htmlacademy-univer-javascript-1/2431705-kekstagram-4 pull request #1
Opened 2023-09-19 16:01 UTC by PavelUd

2023-09-22 10:46 UTC, MaksimovG requested changes

2023-09-22 10:46 UTC, MaksimovG commented on Readme.md
> +* Наставник: Геннадий Максимов.
Необходимо записать в стиле разметки, как написаны ваши данные (скобки, ссылка). При открытии таких файлов такая разметка превратится в ссылку. Пул реквест повторно создавать не надо. Сделайте еще один коммит и запушьте его

2023-09-22 11:41 UTC, PavelUd reviewed
gg

2023-09-24 12:01 UTC, MaksimovG approved these changes

2023-09-24 12:01 UTC, merged