Module9 task2
htmlacademy-univer-javascript-1/2431705-kekstagram-4 pull request #10
Opened 2023-12-12 09:36 UTC by PavelUd

2023-12-12 16:45 UTC, MaksimovG requested changes

2023-12-12 16:45 UTC, MaksimovG commented on js/form.js
> +const RIGHT_HASHTAG = /^#[А-яа-яA-za-zёЁ]{1,19}$/;
название переменной не соответсвует ее содержимому

2023-12-12 16:45 UTC, MaksimovG commented on js/form.js
> +const EffectsFilter = document.querySelector('.img-upload__effects');
почему с большой буквы

2023-12-12 16:45 UTC, MaksimovG commented on js/image-effects.js
> +const EFFECTS = {
в общем с этой переменной всегда сложности в трактовке, Но это точно не массив, а значит не сущ во множественном числе. Так что  Effect

2023-12-12 16:45 UTC, MaksimovG commented on js/image-effects.js
> +  if(effect === 'none'){
вытащить none из константы Effect и сравнивать с ним

2023-12-12 16:45 UTC, MaksimovG commented on js/image-scale.js
> +  scaleSmaller.removeEventListener('click', onScaleButtonClick);
у каждой кнопк свой обработчик должен быть.

2023-12-14 12:25 UTC, MaksimovG requested changes

2023-12-14 12:25 UTC, MaksimovG commented on js/form.js
> +};
ErrorMessage
перечитывайте критерии

2023-12-14 12:25 UTC, MaksimovG commented on js/image-effects.js
> +const EFFECT = {
Effect

2023-12-14 12:25 UTC, MaksimovG commented on js/image-effects.js
> +const DefaultSliderParams = {
param

2023-12-15 13:52 UTC, MaksimovG requested changes

2023-12-15 13:52 UTC, MaksimovG commented on js/form.js
> +  hashTag: 'Уникальные хештеги, каждый не более 20 символов, должны быть разделены пробелом',
BAD_HASHTAG: '',
BAD_COMMENT: '',

2023-12-15 13:52 UTC, MaksimovG commented on js/image-effects.js
> +  }
NONE CHROME и тд

2023-12-15 13:52 UTC, MaksimovG commented on js/image-effects.js
> +  range: {min: 0, max: 100},
форматирование как везде должно быть ( перенос на др строки)

2023-12-15 13:52 UTC, MaksimovG commented on js/image-effects.js
> +  image.style.filter = Effect['none'].name;
none в константу

2023-12-15 13:52 UTC, MaksimovG commented on js/image-effects.js
> +  const effect = evt.target.value;
evt.target.value.toUpperCase() - чтобы под новый формат константы соответствовать

2023-12-15 14:16 UTC, PavelUd commented on js/image-effects.js
> +  range: {min: 0, max: 100},
я не понял

2023-12-16 12:54 UTC, MaksimovG requested changes

2023-12-16 12:54 UTC, MaksimovG commented on js/image-effects.js
> +const NONE = 'NONE';
DEFAULT_FILTER

2023-12-16 12:54 UTC, MaksimovG commented on js/image-effects.js
> +};
В итоге получился не модуль а файл с набором функций. Если делаете модуль, делайте его инкапсулированым, без лишго путающего и ненужного экспорта его внутренних органов ( слушателей, или каких-то функций внтуреннего жизненного цикла). Создайте функции которые запускают модуль (вешают обработчики событий, меняют классы), тормозят модуль (ставят все значения в дефолт, удаляют обработчики и тд) и возможно меняют его состояние (допустим нужно просто вернуть все в дефолт

2023-12-16 12:54 UTC, MaksimovG commented on js/image-scale.js
> +
вот здесь же нормально сделали

2023-12-17 09:32 UTC, MaksimovG requested changes

2023-12-17 09:32 UTC, MaksimovG commented on js/image-scale.js
> +const onScaleSmallerClick = updateScale;
(evt) => updateScale(evt.target.dataset.value);

2023-12-17 09:32 UTC, MaksimovG commented on js/image-scale.js
> +const onScaleSmallerClick = updateScale;
и соответственно поправить updateScale

2023-12-17 09:32 UTC, MaksimovG commented on js/image-effects.js
> +};
DefaultSliderParam = {
  RANGE: {min: 0, max: 100}, START: 100, STEP: 0.1
};

2023-12-17 10:15 UTC, PavelUd commented on js/image-effects.js
> +};
к сожалению,  noUiSlider не поддерживает ваши критерии

2023-12-17 10:16 UTC, merged