первый раз
htmlacademy-univer-javascript-1/2431705-kekstagram-4 pull request #4
Opened 2023-10-15 17:44 UTC by PavelUd

2023-10-19 10:25 UTC, MaksimovG requested changes

2023-10-19 10:25 UTC, MaksimovG commented on js/main.js
> +import {getRandomNumberFromInterval} from './util.js';
вызов функции getThumbnails оставить в main а все остальное перенести в data

2023-10-22 11:52 UTC, MaksimovG approved these changes

2023-10-22 11:54 UTC, MaksimovG requested changes

2023-10-22 11:54 UTC, MaksimovG commented on js/data.js
> +const constructComments = (quantity, id) => new Array(quantity).fill('').map((_, messageId) => {
название не соответсвует критериям

2023-10-22 11:54 UTC, MaksimovG commented on js/data.js
> +export const getThubnails = () =>
thumbnails. но лучше getPhotos (нам еще это название getThumbnails) пригодится

2023-10-23 08:21 UTC, MaksimovG requested changes

2023-10-23 08:21 UTC, MaksimovG commented on index.html
> +  <script type="module" src="/js/data.js"></script>
убрать первый /

2023-10-23 08:21 UTC, MaksimovG commented on js/data.js
> +
лишняя строка

2023-10-23 08:21 UTC, MaksimovG commented on js/data.js
> +const comments = (quantity, id) => new Array(quantity).fill('').map((_, messageId) => {
функция названа не в соответсвии с критериями

2023-10-23 08:21 UTC, MaksimovG commented on js/data.js
> +export const photoDescriptions = () =>
функция названа не в соответствии с критериями

2023-10-23 08:26 UTC, PavelUd commented on js/data.js
> +const comments = (quantity, id) => new Array(quantity).fill('').map((_, messageId) => {
эм, а что в первом разе не так? и что конкретно не соответствует критериям в названии "constructComments". Ведь глагол Construct есть и написано camelCase.

2023-10-23 14:29 UTC, MaksimovG approved these changes

2023-10-23 14:29 UTC, MaksimovG commented on js/main.js
> +getPhotoDescriptions();
getPhotoData

2023-10-23 14:30 UTC, merged